---
title: "Life Expectancy"
author: "Tom Saunders"
date: "2023-12-23"
output: html_document
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = file.path(dirname(inputFile), 'index.html')) })
---
```{r, message=FALSE}
library(readr)
library(dplyr)
library(ggplot2)
```

```{r, message=FALSE}
life_exp <- read_csv("data/DP_LIVE_11122023092440528.csv")
health_spend <- read_csv("data/SHA_11122023093838475.csv")
```

```{r}
exp2020 <- life_exp |> 
  filter(TIME == 2020 & SUBJECT == "TOT") |> 
  group_by(LOCATION) |> 
  summarise(
    years = Value
  )
```

```{r, warning=FALSE}
# Plot per capita government spending on health

spend2020_govt <- health_spend |> 
  filter(
    `Financing scheme` == "Government/compulsory schemes",
    Provider == "All providers",
    Measure == "Per capita, current prices, current PPPs",
  ) |> 
  group_by(LOCATION) |> 
  summarise(
    total = sum(Value)
  )

full <- full_join(spend2020_govt, exp2020,
          by = "LOCATION")

ggplot(full, aes(total, years)) +
  geom_point() +
  theme_classic()
```